replicaCount: 1

image:
  repository: ghcr.io/nimanisha/charts/backend-chart 
  tag: latest 
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-login

database:
  host: "infrastructure-db-postgresql.db.svc.cluster.local"
  name: "my_database"
  user: "postgres"
  # port: "5432"
  existingSecret: "my-db-postgresql" 

service:
  type: ClusterIP
  port: 8080

serviceAccount:
  create: true
  name: "backend-sa"