replicaCount: 2

image:
  repository: nginx
  tag: alpine

# آدرس بک‌اِند در کلاستر (بین Namespaceها)
backendUrl: "http://backend-service.backend-namespace.svc.cluster.local:8080/api/"

service:
  type: ClusterIP
  port: 80

hpa:
  minReplicas: 2
  maxReplicas: 5
  targetCPU: 80

# محتوای index.html شما اینجا قرار می‌گیرد
indexHtml: |
  <!DOCTYPE html>
  ... (کد HTML شما با API_URL = '/api/users') ...