name: Vyking backend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'applications/Backend/**'
      - '.github/workflows/Backend-docker.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin      
      - name: Build and push Docker image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/backend-app
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker build applications/Backend/ -t $IMAGE_ID:latest -t $IMAGE_ID:${{ github.run_number }}
          docker push $IMAGE_ID --all-tags

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Package and Push Helm Chart (OCI)
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin          
          CHART_VER="1.0.${{ github.run_number }}"
          helm package applications/Backend/backend-chart --version $CHART_VER
          LOWER_OWNER=$(echo "${{ github.repository_owner }}" | tr '[A-Z]' '[a-z]')
          helm push backend-chart-*.tgz oci://ghcr.io/$LOWER_OWNER/charts