name: Release Frontend Charts

on:
  push:
    branches: [ "main" ] 
    paths:  
      - 'applications/Frontend/**'
      - '.github/workflows/Frontend-docker.yml' 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          echo "${{ secrets.GH_PAT }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          LOWER_REPO=$(echo "${{ github.repository_owner }}" | tr '[A-Z]' '[a-z]')
          IMAGE_ID=ghcr.io/$LOWER_REPO/frontend-app           
          docker build applications/Frontend/ -t $IMAGE_ID:latest -t $IMAGE_ID:${{ github.run_number }}
          docker push $IMAGE_ID --all-tags

      - name: Package and Push OCI
        run: |
          CHART_PATH="applications/Frontend/frontend-chart"
          CHART_VERSION=$(grep '^version:' $CHART_PATH/Chart.yaml | awk '{print $2}' | tr -d '"' | tr -d "'")
          NEW_VERSION="${CHART_VERSION}.${{ github.run_number }}"

          echo "Building Frontend Chart version: $NEW_VERSION"
          helm package $CHART_PATH --version $NEW_VERSION
          
          LOWER_OWNER=$(echo "${{ github.repository_owner }}" | tr '[A-Z]' '[a-z]')
          helm push frontend-chart-$NEW_VERSION.tgz oci://ghcr.io/$LOWER_OWNER/charts